### PR TITLE
Dependencie and Compatibility Update

### PR DESCRIPTION
**Pull request by chaosfreak93**
- Bump Gradle to 7.0.4
- Bump Gradle Wrapper to 7.0.2
- Bump Target Android API to 31
- Bump Java Version to 11
- Bump Build Tools to 31.0.0
- Replace JCenter with MavenCentral
- Bump App Version to 1.0.8
- Update Changelog
- Update Copyright

### CODE REVIEW

**Comment by chaosfreak93** [comment]
Draft until i tested the app on multiple phones and android versions

**Review by chaosfreak93 — COMMENTED** [review]
Thx i forgot this

**Comment by justdave** [comment]
Looks good so far, thanks for all the help!

**Comment by chaosfreak93** [comment]
This PR is done, maybe i will make a rework or redesign of the app, over the holidays, to finish some open issues.

**Pull request merged**
