### PR TITLE
Use Modern design on Android API 21 and above

### PR DESCRIPTION
**Pull request by chaosfreak93**

### CODE REVIEW

**Comment by chaosfreak93** [comment]
#23

**Comment by justdave** [comment]
The only noticeable change with this applied is that the app icon is no longer on the left end of the status bar, and the title font is slightly thicker.  Is that what's intended?  (I guess it provides better OS integration or something)

**Comment by chaosfreak93** [comment]
The dialog boxes and the edit bar also changed a bit. I just wanted that the app looks a little bit modern.

**Comment by justdave** [comment]
OK, I see it.  Yeah, I was just making sure it wasn't supposed to be a more drastic change than that or something.
Looks nice.

Just so I don't repeat last night's mistakes, is this ready to go?

**Comment by chaosfreak93** [comment]
Yes, I think it's okay so. Merge if you want.

**Comment by chaosfreak93** [comment]
Or wait. What about the changelog?

**Comment by justdave** [comment]
yeah, wouldn't hurt to update that, too.
* Support Material Design on Android 4.4 (KitKat) and newer.

**Pull request merged**
